name: Selenium Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Navigate to SeleniumProject directory
    - name: Change Directory to SeleniumProject
      working-directory: ./SeleniumProject
      run: pwd
      
    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set up Chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./SeleniumProject

    # Execute tests with gradlew
    - name: Execute gradlew
      run: ./gradlew cucumber
      working-directory: ./SeleniumProject

    # Upload HTML report as an artifact
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-html-report
        path: ./SeleniumProject/reports/cucumber-html-reports
